---
# NOTE: That didn't work, thus use of instance with nested virtualization enabled.

compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 4
  memory: 16G
  disk: 100
  nested_virtualization: true

# environment variables

env:
  MINIO_ACCESS_KEY: "ENCRYPTED[d41e1754ceb6184154c3e0cc78ad41e1e58514bfc0d797427c79d15a4207c5d329fe2b28f9a254c1600f9f076cc54f53]"
  MINIO_SECRET_KEY: "ENCRYPTED[567abd4bd6cdff9509bf58d690220bb56a760e9dec1f11effef1d913e7a9c1a90fff41c57ae685ea4a87c7e14bfd8174]"

# task templates

build_task:
  install_script:
    - apt-get update
    - apt-get install -y genisoimage coreutils syslinux-utils p7zip-full
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod 0755 mc
    - ./mc alias set minio https://minio.services.osism.tech $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

  build_script:
    - make create-image

  push_script: |
    if [ "$CIRRUS_BRANCH" == "main" ]; then
      ./mc cp /dev/shm/osism-manager-installer.iso minio/manager-installer
      ./mc policy set download minio/manager-installer
    fi
