---
# NOTE: That didn't work, thus use of instance with nested virtualization enabled.

compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 4
  memory: 16G
  disk: 100
  nested_virtualization: true

# environment variables

env:
  MINIO_ACCESS_KEY: "ENCRYPTED[d41e1754ceb6184154c3e0cc78ad41e1e58514bfc0d797427c79d15a4207c5d329fe2b28f9a254c1600f9f076cc54f53]"
  MINIO_SECRET_KEY: "ENCRYPTED[567abd4bd6cdff9509bf58d690220bb56a760e9dec1f11effef1d913e7a9c1a90fff41c57ae685ea4a87c7e14bfd8174]"

# task templates

build_task:
  install_script:
    - apt-get update
    - apt-get install -y genisoimage coreutils syslinux-utils
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc alias set minio https://minio.services.osism.tech $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

  download_script:
    - wget -O ./ubuntu-image.iso https://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/ubuntu-20.04.1-legacy-server-amd64.iso

  mount_script:
    - mkdir /dev/shm/ubuntu-seed
    - mkdir ./ubuntu-iso
    - mount -o loop,ro ./ubuntu-image.iso ./ubuntu-iso/
    - cp -rT ./ubuntu-iso /dev/shm/ubuntu-seed
    - umount ./ubuntu-iso/

  prepare_script:
    - cp ./isoconf/grub.cfg /dev/shm/ubuntu-seed/boot/grub/grub.cfg
    - cp ./isoconf/txt.cfg /dev/shm/ubuntu-seed/isolinux/txt.cfg
    - cp ./isoconf/osism-ubuntu-server.seed /dev/shm/ubuntu-seed/preseed/osism-ubuntu-server.seed
    - sed -i "s|boot/grub/grub.cfg$||g" /dev/shm/ubuntu-seed/md5sum.txt
    - cd /dev/shm/ubuntu-seed/
    - md5sum ./boot/grub/grub.cfg >> /dev/shm/ubuntu-seed/md5sum.txt
    - md5sum ./preseed/osism-ubuntu-server.seed >> /dev/shm/ubuntu-seed/md5sum.txt

  build_script:
    - cd /dev/shm/ubuntu-seed/
    - mkisofs -U -A "UbuntuOSISM" -V "UbuntuOSISM" -volset "UbuntuOSISM" -J -joliet-long -r -v -T -o /dev/shm/osism-manager-installer.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot /dev/shm/ubuntu-seed/
    - isohybrid /dev/shm/osism-manager-installer.iso

  push_script:
    - ./mc cp /dev/shm/osism-manager-installer.iso minio/manager-installer
    - ./mc policy set download minio/manager-installer
